### ISSUE TITLE
Fix biga_gran UVs and biga_simple normal map texture

### ISSUE THREAD

**Issue by alexei-anticto** [anticto/steamroll#879]

**Comment by alexei-anticto** [comment]
Fi_terra too

**Comment by alexei-anticto** [comment]
DrPerfo_punxa

**Comment by alexei-anticto** [comment]
T_C_4

**Comment by alexei-anticto** [comment]
Refer UVs Pillar_Path i comprovar mida textures

**Comment by alexei-anticto** [comment]
Refer UVs Terra_B_1 i comprovar mida textures

**Comment by alexei-anticto** [comment]
Peana_Marc

**Comment by emabece** [comment]
- biga_gran done
- Fi_terra not fixed, UVs should be redone (pending)
- biga_simple, Terra_C_4 and Terra_B_1 don't appear in any playable level (only in a couple test levels)
- DrPerfo_punxa is only 1/4 of UV map because it belongs to a part of a texture (Perfo_D, N, R and AO)
- Pillar_Path done and texture set in Max size 512
- Peana_Marc done
